// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0NrTqP6_KoZnlFo2k5dPZ6sHy5eTqs34',
    appId: '1:23443083020:web:0fa57ca9f8874d5950c329',
    messagingSenderId: '23443083020',
    projectId: 'atmapp-df541',
    authDomain: 'atmapp-df541.firebaseapp.com',
    storageBucket: 'atmapp-df541.appspot.com',
    measurementId: 'G-NHSHWM0PVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt3MHsqOld0qEFlxzHw1e2hu62z_jiSXk',
    appId: '1:23443083020:android:8374459171925f6050c329',
    messagingSenderId: '23443083020',
    projectId: 'atmapp-df541',
    storageBucket: 'atmapp-df541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTpJd_48daiBBz_jmY1yBX5IHXRlYGfxU',
    appId: '1:23443083020:ios:15d3eb90df5af24550c329',
    messagingSenderId: '23443083020',
    projectId: 'atmapp-df541',
    storageBucket: 'atmapp-df541.appspot.com',
    iosBundleId: 'com.example.newFingerprintAtm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTpJd_48daiBBz_jmY1yBX5IHXRlYGfxU',
    appId: '1:23443083020:ios:6bf4ffd9634be0af50c329',
    messagingSenderId: '23443083020',
    projectId: 'atmapp-df541',
    storageBucket: 'atmapp-df541.appspot.com',
    iosBundleId: 'com.example.newFingerprintAtm.RunnerTests',
  );
}
